CREATE TABLE uploads (
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    object_key VARCHAR(255) NOT NULL,
    public_url VARCHAR(255) NOT NULL,
    mime_type VARCHAR(100) DEFAULT NULL,
    size BIGINT UNSIGNED NOT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
